import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import { CartProvider } from "./context/CartContext";
import PerformanceObserver from "./components/PerformanceObserver";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CartProvider>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}>
          <PerformanceObserver />
          <Navbar />
          <main>{children}</main>
        </body>
      </CartProvider>
    </html>
  );
}
